# Generated by Django 4.2.4 on 2023-08-16 17:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_image_image_file_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 500], upload_to='post_images/', verbose_name='فایل تصویر'),
        ),
    ]
