# Generated by Django 4.2.4 on 2023-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': 'اکانت ها'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('هوش مصنوعی', 'هوش مصنوعی'), ('برنامه نویسی', 'برنامه نویسی'), ('بلاکچین', 'بلاکچین'), ('امنیت', 'امنیت'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
